openapi: 3.0.1
info:
  title: Decima API
  description: 'External API for Decima. Used by both the included web GUI and external webhooks.'
  license:
    name: MIT
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Test if server is responsive.
      requestBody:
        description: Empty request
        content: {}
responses:

